FROM node:16-alpine

WORKDIR /app

ARG NODE_ENV
ENV NODE_ENV=production
ARG REACT_APP_OPEN_WEATHER_APP_ID
ENV REACT_APP_OPEN_WEATHER_APP_ID=$REACT_APP_OPEN_WEATHER_APP_ID
ARG REACT_APP_SPOTIFY_CLIENT_ID
ENV REACT_APP_SPOTIFY_CLIENT_ID=$REACT_APP_SPOTIFY_CLIENT_ID
ARG REACT_APP_SPOTIFY_CLIENT_SECRET
ENV REACT_APP_SPOTIFY_CLIENT_SECRET=$REACT_APP_SPOTIFY_CLIENT_SECRET
ARG REACT_APP_DEV_REDIRECT_URI
ENV REACT_APP_DEV_REDIRECT_URI=$REACT_APP_DEV_REDIRECT_URI
ARG REACT_APP_REDIRECT_URI
ENV REACT_APP_REDIRECT_URI=$REACT_APP_REDIRECT_URI

COPY . .

RUN npm ci --omit=dev

RUN npm run build:client

CMD ["npm", "run", "app"]
